#@author [Niklas Denneler](https://github.com/niklasden)
# [START env settings]
env: standard
runtime: nodejs12
service: frontend
# [END env settings]

# [START handlers]
handlers:
    - url: /static
      static_dir: build/static
    - url: /(.*\.(json|ico|js))$
      static_files: build/\1
      upload: build/.*\.(json|ico|js)$
    - url: .*
      static_files: build/index.html
      upload: build/index.html
# [END handlers]