version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    volumes:
        - ./er_diagram.sql:/docker-entrypoint-initdb.d/er_diagram.sql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_shoppingproject
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8180:80
  